### ISSUE TITLE
:memo: doc suggestion: zola version

### ISSUE THREAD

**Issue by ymdarake** [bennetthardwick/simple-dev-blog-zola-starter#15]
First of all, thanks for the cool theme!

I happened to find zola and this theme, and built my blog on Netlify just a while ago.
Looking great!

At first, I tried to deploy on Vercel, but because they are using zola `0.13.0` as of today, I got build errors on Vercel, even though locally I had no problems.
As I'm very new to zola, I couldn't notice that it was the version specific issue at first sight.

I'm guessing, from the `netlify.toml`, zola version supposed to be `0.14.0`, 
so I just thought it's nice if I can check which version I should use in `README` or later in `CHANGELOG` or something.

Anyway, much appreciated. Really cool stuff!

**Comment by bennetthardwick** [comment]
Hey, thanks for the feedback! I've updated the "how to get started" section to mention that the theme needs version 0.14 or greater 👍🏻
