### ISSUE TITLE
After reading your zero JS static blog article, it seems that this theme is different from the style demonstrated in your article God bless you

### ISSUE THREAD

**Issue by xiyuvi** [bennetthardwick/simple-dev-blog-zola-starter#19]
After reading your zero JS static blog article, it seems that this theme is different from the style demonstrated in your article God bless you
![image](https://github.com/bennetthardwick/simple-dev-blog-zola-starter/assets/38217058/6c4a5d51-790f-4304-a77f-8bae3a78eb4c)

**Comment by xiyuvi** [comment]
https://bennett.dev/creating-a-blazingly-fast-blog-without-js-or-gatsby/

**Comment by bennetthardwick** [comment]
Hey @xiyuvi I've changed up my website in the last year or so to use React and [Vike](https://vike.dev/) so it doesn't use this theme anymore. I've still got a version of it hosted here though: https://simple-dev-blog-zola-starter.netlify.app/.
