### ISSUE TITLE
icon.png not found

### ISSUE THREAD

**Issue by Lucretiel** [bennetthardwick/simple-dev-blog-zola-starter#3]
When following the instructions in README to create a new sample page, I get this error:

```
Error: Failed to render section 'C:/Users\Lucre\Documents\website\content\_index.md'
Reason: Failed to render 'simple-dev-blog/templates/index.html' (error happened in 'simple-dev-blog/templates/base.html').
Reason: Function call 'resize_image' failed
Reason: `resize_image`: Cannot find path: icon.png
```

Would it be possible to add an example of how an icon should be added? I understand if the theme doesn't want to support the no-icon use case, it would be helpful to have an example of what path the plugin looks for when resolving the icon

**Comment by bennetthardwick** [comment]
Thanks! I've updated the README with some more info about the icon.
