### ISSUE TITLE
Feature request: css styling for footnotes

### ISSUE THREAD

**Issue by Lucretiel** [bennetthardwick/simple-dev-blog-zola-starter#6]
Currently, zola (via [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark)) will generate footnotes from your markdown, at the end of the content. The footnote is rendered like this:

```html
<div class="footnote-definition" id="1">
    <sup class="footnote-definition-label">1</sup>
    <p>This is a footnote.</p>
</div>
```

(though see also https://github.com/raphlinus/pulldown-cmark/issues/464)

If possible it'd be nice to have this be styled more like a footnote; in particular, the current (lack of) css makes the alignment out of whack 
![image](https://user-images.githubusercontent.com/1823405/90565590-28ca6f00-e175-11ea-87b7-b04d3fc1b93a.png)

**Comment by bennetthardwick** [comment]
Boy, they make it hard to style the footnotes! I tried my best to make it look like how [hugo renders](https://bennetthardwick.com/wiki/refactoring/speculative-generality/). Here's the [preview](https://simple-dev-blog-zola-starter.netlify.app/blog/first-blog-post/), if you have any CSS suggestions feel free to make a PR or let me know - I'm not much of a designer.

**Comment by Lucretiel** [comment]
Sure, I'll see what I can do. I agree, I was also having trouble styling them but I am also not much of a css author. Hoping that if https://github.com/raphlinus/pulldown-cmark/issues/464 lands it'll be easier.
