### ISSUE TITLE
Instructions to install theme no longer work?

### ISSUE THREAD

**Issue by sophiajt** [bennetthardwick/simple-dev-blog-zola-starter#7]
I tried following the steps from here: https://www.getzola.org/themes/simple-dev-blog/

But when I try to run `zola serve` at the end, I get:

```
Error: Failed to render section '/home/jonathan/Source/sites/my_amazing_site/content/_index.md'
Reason: Failed to render 'index.html' (error happened in 'base.html').
Reason: Function call 'resize_image' failed
Reason: `resize_image`: Cannot find path: icon.png
```

Any ideas?

**Comment by bennetthardwick** [comment]
Looks like it's trying to find the images specified in the `theme.toml` from the root folder instead of the theme folder. I'll update the instructions to say you should copy the content from the theme into your own content folder.

**Comment by bennetthardwick** [comment]
Hopefully, the updated instructions in 9d6efa8 should work for you. I imagine it'll go live on the Zola website the next time it's updated.

**Comment by sophiajt** [comment]
Yup, those fixed it for me. Thanks!
